# Generated by Django 4.2.7 on 2024-09-22 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0008_taskinfo_delete_deletionresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAI_APIKeyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=255)),
            ],
        ),
    ]
