# Generated by Django 4.2.7 on 2024-09-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0009_openai_apikeyconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteRecordContentGen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=255, unique=True)),
                ('business_domains', models.JSONField(default=list)),
            ],
        ),
    ]
